### ISSUE TITLE
Canlendar widget display as a blank when adjusting time and date

### ISSUE THREAD

**Issue by Adelaxie** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#146]

**Comment by Adelaxie** [comment]
fixed by initialized it.

**Comment by alex998r** [comment]
Ok, sorry to not have seen that before. I have a new info for you, saturday I went to the flying field and the date was updated!!! The calendar correctly shows, probably was due to the GPS that gained the FIX passing data to the radio, the previous failure was noted in my home, so without GPS signals.
Thanks

**Comment by janekx** [comment]
Remember we had allready this bug in past

**Comment by Adelaxie** [comment]
@alex998r  It still need more test, please pay attention on next release to test. Thanks in advance.
